apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: skld6p8ay-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: skld6p8ay-nodejs 
  name: skld6p8ay-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: skld6p8ay-nodejs 
